# Generated by Django 3.1.5 on 2021-02-11 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendsUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('profile_background', models.ImageField(default='../../public/static/img/background.jpg', upload_to='../../data/media')),
                ('profile_picture', models.ImageField(default='../../public/static/img/background.jpg', upload_to='../../data/media')),
                ('nickname', models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001E70197C370>', max_length=40, unique=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('gender', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nothing', 'Prefiro não dizer')], default='nothing', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
