# Generated by Django 3.1.5 on 2021-01-26 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendsUser',
            fields=[
                ('profile_background', models.ImageField(upload_to='')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('nickname', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('gender', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nothing', 'Prefiro não dizer')], default='nothing', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
