# Generated by Django 3.1.5 on 2021-02-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsuser',
            name='profile_picture',
            field=models.ImageField(upload_to='D:\\Entra21\\Cyberzone\\data/media'),
        ),
    ]
