# Generated by Django 3.1.5 on 2021-02-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsuser',
            name='nickname',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x00000185B5D0C370>', max_length=40, unique=True),
        ),
    ]
