# Generated by Django 3.1.5 on 2021-02-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210209_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsuser',
            name='profile_picture',
            field=models.ImageField(upload_to='../../data/media'),
        ),
    ]
