# Generated by Django 3.1.5 on 2021-02-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210210_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsuser',
            name='nickname',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x689b322d1be0>', max_length=40, unique=True),
        ),
    ]
