# Generated by Django 3.1.5 on 2021-02-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_extendsuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsuser',
            name='profile_background',
            field=models.ImageField(default='static/background.jpg', upload_to='user/background'),
        ),
        migrations.AlterField(
            model_name='extendsuser',
            name='profile_picture',
            field=models.ImageField(default='static/usuario.jpg', upload_to='user/profile'),
        ),
    ]
