# Generated by Django 3.1.5 on 2021-02-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210213_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsuser',
            name='profile_background',
            field=models.ImageField(default='default/background.jpg', upload_to='user/background'),
        ),
        migrations.AlterField(
            model_name='extendsuser',
            name='profile_picture',
            field=models.ImageField(default='default/usuario.jpg', upload_to='user/profile'),
        ),
    ]
